version: 2
jobs:
  test:
    working_directory: ~/secure-proxy
    docker:
      - image: circleci/node:12
        environment:
          FIREFOX_PATH: /tmp/firefox/firefox
          XPI_PATH: /tmp/secure-proxy.xpi
          HEADLESS: y
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create the XPI
          command: npm run-script build
      - run:
          name: Run the tests
          command: PATH=$PATH:/tmp npm run experimentaltests
workflows:
  version: 2
  build-test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
